server:
  port: 9010
spring:
  config:
    import:
      - classpath:EventDrivenConfigs.yml
  application:
    name: "message"

logging:
#  level:
#    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
