spring:
  cloud:
    function:
      definition: email|sms # putting this it will create input and output bindings automatically
    stream:
      bindings:
        emailsms-out-0: # this will create a exchange and bind it to the queue provided.
          destination: communication-sent
        emailsms-in-0: # this will create a queue in the rabbitmq.
          destination: send-communication
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092