spring:
  cloud:
    function:
      definition: updateCommunication # putting this it will create input and output bindings automatically
    stream:
      bindings:
        updateCommunication-in-0: # this will create a queue in the rabbitmq.
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0: # this will create a exchange and bind it to the queue provided.
          destination: send-communication
      kafka:
        binder:
          brokers:
            - localhost:9092