server:
  port: 8080
spring:
  application:
    name: "accounts" # this should be same name as of what we kept in configuration server yamls. so that client is gonna call server using this name
  # using default profile incase not provided anything. and importing the yamls using the api call.
  profiles:
    active: "default"
  config:
    import: "configserver:http://localhost:8071/"# we can also use optional:configserver which will make this is optinal and starts the app
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  this will import the another yml. As iam gonna implement a config server. commenting this out!!!
#  config:
#    import:
#      - application_test.yml
#  # this will set active profile as test. and common properties will be overriden by values in test yml!!
#  profiles:
#    active:
#      -test

build:
  version: "2"
contact-Info:
  info:
    name: Hemanth
    email: ssgkhemanth99@gmail.com
  phoneNumber:
    - "9581327524"
    - "7207492325"
  implemented_date: "2024-02-09"


