server:
  port: 9010
spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms # putting this it will expose another endpoint named emailsms, when called. both the functions are called.

logging:
#  level:
#    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
