spring:
  config:
    active:
      on-profile: "test"

build:
  version: 3
contact-Info:
  info:
    name: HemanthInCards
    email: amalapurapuhemanth@gmail.com
  phoneNumber:
    - "9581327524"
    - "7207492325"
  implemented_date: "2024-02-09"